### PR TITLE
fix: update dependency schematics-utilities

### PR DESCRIPTION
**Pull request by jingfee**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe: update a dependency to avoid vulnerability

## What is the current behavior?

Issue Number: #666

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Thanks for the PR. Did you test that it works?

**Comment by jingfee** [comment]
> 
> 
> Thanks for the PR. Did you test that it works?

Hi, thanks for having a look. I did check that it was still building without error, that all the test passed and I also checked the changelog for schematics-utilities v2 and it didn't seem to have any changes which impacted the methods used here. Is it possible to also run an actual schematic against the playground application to check that everything looks fine there?

**Comment by NetanelBasal** [comment]
Yes, you can npm link the dist folder to any angular project and run it.

**Comment by jingfee** [comment]
Will do and get back to you :thumbsup:

**Comment by jingfee** [comment]
Tested running schematics without any issues.

**Pull request merged**
