### PR TITLE
feat(akita): more typesafe EntityState

### PR DESCRIPTION
**Pull request by RobinVdBroeck**
This deletes the {[key: string]: any} from the definiton of EnityState.
This is breaking change, because users of akita might have failing
typechecking now. (However, this should have failed either way, since it
was not correct.)

See #744 for the reasoning behind this change.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] Other... Please describe: Typesafety

## What is the current behavior?

Issue Number: #744

## Does this PR introduce a breaking change?

- [X] Yes
- [ ] No

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Check if this code works:

```ts
export interface TodosState extends EntityState<Todo, number> {
  filter: string;
}

@StoreConfig({ name: 'todos' })
export class TodosStore extends EntityStore<TodosState> {
  constructor() {
    super({ filter: 'ALL' });
  }
}
```

**Comment by RobinVdBroeck** [comment]
> Check if this code works:
> 
> ```ts
> export interface TodosState extends EntityState<Todo, number> {
>   filter: string;
> }
> 
> @StoreConfig({ name: 'todos' })
> export class TodosStore extends EntityStore<TodosState> {
>   constructor() {
>     super({ filter: 'ALL' });
>   }
> }
> ```

It does. I've also added an extra test case for this.

**Comment by NetanelBasal** [comment]
When you run `npm run start` it compiles?

**Comment by NetanelBasal** [comment]
There will be a problem with the `active` property. Let me know if you can handle it.

**Comment by RobinVdBroeck** [comment]
> There will be a problem with the `active` property. Let me know if you can handle it.

I'm currently looking into it. I hope to have something ready by the start of next week.

**Comment by RobinVdBroeck** [comment]
It looks like EntityStore expects the given EntityState to also be either a ActiveState or MultiActiveState for functions like getActive(), setActions() and updateActive(). What's the design decision behind this? Should EntityStore work without active?

**Comment by NetanelBasal** [comment]
Yes, it's optional. The consumer should pass it. We can solve it by something like:

```ts
S extends { active: any } ? S['active'] : never
```

**Comment by RobinVdBroeck** [comment]
> Yes, it's optional. The consumer should pass it. We can solve it by something like:
> 
> ```ts
> S extends { active: any } ? S['active'] : never
> ```
I was thinking about using never to. However, this is valid typescript:

```typescript
declare let a: never;
let b: any = a;
```
[playground](https://www.typescriptlang.org/play?ts=4.3.5&ssl=3&ssc=16&pln=1&pc=1#code/CYUwxgNghgTiAEEQBd5QFzwHYgG4hgG4AoYpVAI0yiwE94BeNQoA)

I think we can live with that. If the consumer of the api uses any, they are throwing type checking away either way.

**Comment by RobinVdBroeck** [comment]
I don't get it compiling, can you take a look at it?

**Pull request closed without merging**
