### PR TITLE
fix(ng-entity-service): remove duplicated file

### PR DESCRIPTION
**Pull request by TheAifam5**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 0

## What is the new behavior?
None

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
I selected that as a bugfix, because files — depends on a platform — can be case-sensitive and case-insensitive, which in the second case can lead to errors about duplicated file, based on its name.

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Where do you see this file? I have only one file.

**Comment by TheAifam5** [comment]
988A57B9-FACD-4BA5-8F95-A431EA75C6DF

**Comment by NetanelBasal** [comment]
For some reason I can't see it my local machine.

**Comment by TheAifam5** [comment]
Are you using Windows?

**Comment by cmalard** [comment]
I can see it too :+1: (both identical)

**Pull request merged**
