### PR TITLE
feat(persist-state): add ability to select store data to persist

### LINKED ISSUE #373: Excluding store property from persisting
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```typescript
export interface FormState {
  isSubmitting: boolean;
  isEditing: boolean;
  isChecking: boolean;
  isOk: boolean;
  isFullScreen: boolean;
  isReverting: boolean;
}

persistState({ 
  include: ['form'] 
});
```

## Expected behavior
It would be nice to have an option to exclude a certain store property, like this:

```typescript
persistState({ 
  exclude: ['form.isReverting'] 
});

```
## What is the motivation / use case for changing the behavior?

This would be very handy in case of large number of stores and stores with large number of properties. I know that there are the custom hooks, but they don't seem to be very elegant in solving this case. You must keep store in sync with custom hook, which can lead to bugs.

## Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.1
Node: 13.8.0
OS: darwin x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

### PR DESCRIPTION
**Pull request by theorlovsky**
closes #373

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #373 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by theorlovsky** [comment]
@NetanelBasal could you please check the PR? If everything's ok I'll update the tests and docs.

**Comment by NetanelBasal** [comment]
LGTM

**Comment by NetanelBasal** [comment]
We'll release v5 this week. Do you think you're going to make it?

**Comment by theorlovsky** [comment]
Yes, I'm gonna complete this tomorrow. Sorry for the delay, I wasn't able to get back to it last week.

**Comment by NetanelBasal** [comment]
No problem. Make sure to pull master, I've removed the deprecated `exclude` property.

**Comment by theorlovsky** [comment]
@NetanelBasal the documentation on https://netbasal.gitbook.io/akita/enhancers/persist-state looks different from the one in `docs/docs/enhancers/persist-state.mdx`. Is this a right file?

**Comment by NetanelBasal** [comment]
The gitbook is deprecated.

**Comment by theorlovsky** [comment]
@NetanelBasal the PR is ready

**Pull request merged**
