### PR TITLE
fix(build): update nx to 9.4.0

### PR DESCRIPTION
**Pull request by xbaun**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the new behavior?

Update nx to 9.4.0 to fix https://github.com/nodejs/node/issues/32852 when building akita with node v12/v13.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by NetanelBasal** [comment]
https://github.com/datorama/akita/runs/771327457?check_suite_focus=true

**Comment by xbaun** [comment]
Probably the problem is that node_modules is cached: https://github.com/datorama/akita/runs/771322765?check_suite_focus=true#step:4:8

**Comment by NetanelBasal** [comment]
But it should invalidate it when yarn.lock changes.

**Comment by xbaun** [comment]
It's just a guess by me, because the build action ran on my branch without any errors and nx is using  the `node_modules/.cache` folder for caching build targets.

**Comment by NetanelBasal** [comment]
Let's remove the cache and see if it works.

**Comment by NetanelBasal** [comment]
Released.

**Pull request merged**
