### PR TITLE
feat(entity-query): hasEntity with array of ID

### PR DESCRIPTION
**Pull request by jocactus**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

hasEntity() only support ID

Issue Number: #98

## What is the new behavior?
hasEntity() will also support an array of ID

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by NetanelBasal** [comment]
I'm not sure what you did. Didn't you write the feature?

**Comment by jocactus** [comment]
To be honest, It was my first PR at all and I am fairly new to GItHub too.. So I wasn't sure about what you asked me to do..

**Comment by NetanelBasal** [comment]
Never mind, I will add it. To be clear, when you call the following code:
`hasEntity([1, 2, 3])`
It will return `true` only if all of them exists.

**Comment by jocactus** [comment]
In my project, a user can have a list of services. I would like to check first if my services are not in the store before to do a call to the database.

**Pull request closed without merging**
